/** Render native Python models to an explicit preview directory. */
import { createFromJson } from 'codama';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { renderPaymentChannelsPython } from './render-payment-channels-python.js';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..', '..');

/** Render the entire package before touching an existing output directory. */
export function generatePaymentChannelsPython(outputDir: string, check = false): void {
    const idl = fs.readFileSync(path.join(repoRoot, 'idl/payment-channels.json'), 'utf8');
    const files = renderPaymentChannelsPython(createFromJson(idl).getRoot());
    const target = path.resolve(outputDir);
    if (target === repoRoot || repoRoot.startsWith(`${target}${path.sep}`)) {
        throw new Error('The generated package must not replace the repository or an ancestor.');
    }
    if (fs.existsSync(target)) {
        if (!fs.lstatSync(target).isDirectory()) throw new Error('Output must be a directory, not a file or symlink.');
        for (const entry of fs.readdirSync(target, { recursive: true }).map(String)) {
            const current = path.join(target, entry);
            const stat = fs.lstatSync(current);
            if (stat.isSymbolicLink()) throw new Error('Output must not contain symlinks.');
            if (stat.isDirectory()) continue;
            if (!stat.isFile()) throw new Error('Output must contain only regular generated files.');
            if (entry.split(path.sep).includes('__pycache__') && entry.endsWith('.pyc')) continue;
            if (!entry.endsWith('.py')) throw new Error('Output contains non-generated files.');
            const header = fs.readFileSync(current, 'utf8').slice(0, 256);
            if (!/Generated from idl\/payment-channels.json|AUTOGENERATED using the codama library/.test(header)) {
                throw new Error('Refusing to replace an output directory containing non-generated files.');
            }
        }
    }
    const previous = fs.existsSync(target)
        ? fs.readdirSync(target, { recursive: true }).filter((entry) => String(entry).endsWith('.py')).map(String).sort()
        : [];
    const expected = [...files.keys()].sort();
    const same = JSON.stringify(previous) === JSON.stringify(expected)
        && expected.every((file) => fs.readFileSync(path.join(target, file), 'utf8') === files.get(file));
    if (check) {
        if (!same) throw new Error('Native generated Python output differs; regenerate and review it.');
        return;
    }
    if (same) return;
    fs.mkdirSync(path.dirname(target), { recursive: true });
    const temporary = fs.mkdtempSync(path.join(path.dirname(target), '.python-codegen-'));
    const backup = `${temporary}.previous`;
    try {
        for (const [file, content] of files) {
            const destination = path.join(temporary, file);
            fs.mkdirSync(path.dirname(destination), { recursive: true });
            fs.writeFileSync(destination, content);
        }
        if (fs.existsSync(target)) fs.renameSync(target, backup);
        try {
            fs.renameSync(temporary, target);
        } catch (error) {
            if (fs.existsSync(backup)) fs.renameSync(backup, target);
            throw error;
        }
        fs.rmSync(backup, { recursive: true, force: true });
    } finally {
        fs.rmSync(temporary, { recursive: true, force: true });
    }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
    const args = process.argv.slice(2);
    if (args[0] !== '--output' || !args[1] || args.length > 3 || (args[2] && args[2] !== '--check')) {
        throw new Error('Usage: tsx generate-payment-channels-native-py.ts --output <package-directory> [--check]');
    }
    generatePaymentChannelsPython(args[1], args[2] === '--check');
}
